-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;

-- Drop the existing game table if it exists to avoid conflicts
DROP TABLE IF EXISTS public.game CASCADE;

CREATE TABLE IF NOT EXISTS public.game
(
    id serial NOT NULL,
    serie integer,
    id_tournament integer,
    event character varying,
    site character varying COLLATE pg_catalog."default",
    white_name character varying COLLATE pg_catalog."default", -- Changed from white to white_name
    black_name character varying COLLATE pg_catalog."default", -- Changed from black to black_name
    result character(10) COLLATE pg_catalog."default",
    datetime timestamp,
    whiteelo integer,
    blackelo integer,
    whiteratingdiff integer,
    blackratingdiff integer,
    eco character varying COLLATE pg_catalog."default",
    opening character varying COLLATE pg_catalog."default",
    timectl character varying,
    term character varying COLLATE pg_catalog."default",
    analyzed boolean,
    nb_moves integer,
    hash_code character varying COLLATE pg_catalog."default",
    CONSTRAINT game_pkey PRIMARY KEY (id),
    CONSTRAINT game_hash_code_key UNIQUE (hash_code)
);

CREATE TABLE IF NOT EXISTS public.moves
(
    game_id integer NOT NULL,
    "ORDER" integer NOT NULL,
    w_cell character varying COLLATE pg_catalog."default",
    w_eval character varying,
    w_timestamp time without time zone,
    b_cell character varying COLLATE pg_catalog."default",
    b_eval character varying,
    b_timestamp time without time zone,
    CONSTRAINT moves_pkey PRIMARY KEY (game_id, "ORDER")
);

CREATE TABLE IF NOT EXISTS public.player
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL UNIQUE,
    elo_classic integer,
    elo_blitz integer,
    elo_fast integer,
    elo_bullet integer,
    title character varying COLLATE pg_catalog."default",
    classement integer,
    nb_game integer,
    ratio double precision,
    ratio_white double precision,
    ratio_black double precision,
    nb_move_to_win double precision,
    creation_date date,
    favorite_open character varying COLLATE pg_catalog."default",
    CONSTRAINT player_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tournament
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tournament_pkey PRIMARY KEY (id)
);


CREATE TABLE public.chess_openings (
    id integer NOT NULL,
    site character varying(100),
    white_move character varying(100),
    black_move character varying(100),
    moves text
);


ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT game_id_tournament_fkey FOREIGN KEY (id_tournament)
    REFERENCES public.tournament (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT game_black_name_fkey FOREIGN KEY (black_name)
    REFERENCES public.player (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.game
    ADD CONSTRAINT game_white_name_fkey FOREIGN KEY (white_name)
    REFERENCES public.player (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public.moves
    ADD CONSTRAINT moves_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.game (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
